# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='field',
            field=models.CharField(choices=[('1', '金融产品'), ('2', '电信产品'), ('3', '物联网相关')], default='未设置', max_length=30, verbose_name='所属领域'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('1', '立项阶段'), ('2', '开发阶段'), ('3', '测试阶段'), ('4', '提交掩膜')], default='未开始', max_length=30, verbose_name='项目状态'),
        ),
    ]
