# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171014_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='项目中的成员'),
        ),
    ]
