# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 14:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_projectusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFirstCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='子任务名')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects', verbose_name='父项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '一级类别',
                'verbose_name_plural': '一级类别',
            },
        ),
        migrations.AlterModelOptions(
            name='projectusers',
            options={'verbose_name': '项目成员关联表', 'verbose_name_plural': '项目成员关联表'},
        ),
    ]
