# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20171014_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfirstcategory',
            options={'verbose_name': '子任务', 'verbose_name_plural': '子任务'},
        ),
    ]
