# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 21:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20171014_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='阶段名')),
                ('progress', models.IntegerField(default=0, verbose_name='任务进度')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '子任务',
                'verbose_name_plural': '子任务',
            },
        ),
        migrations.CreateModel(
            name='MissionUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Missions', verbose_name='任务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '任务成员关联表',
                'verbose_name_plural': '任务成员关联表',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='阶段名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '阶段',
                'verbose_name_plural': '阶段',
            },
        ),
        migrations.RemoveField(
            model_name='projectfirstcategory',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectfirstcategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectFirstCategory',
        ),
        migrations.AddField(
            model_name='missions',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Stages', verbose_name='所属项目'),
        ),
    ]
