# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20171017_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missions',
            old_name='project',
            new_name='stage',
        ),
    ]
