# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171017_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='任务名'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Stages', verbose_name='所属阶段'),
        ),
    ]
