# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20171018_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='任务详细'),
        ),
    ]
