# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_missions_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='项目开发者'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='field',
            field=models.CharField(choices=[('1', '金融产品'), ('2', '电信产品'), ('3', '物联网相关')], default='未设置', max_length=30, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('1', '立项阶段'), ('2', '开发阶段'), ('3', '测试阶段'), ('4', '结项')], default='未开始', max_length=30, verbose_name='项目阶段'),
        ),
    ]
