# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180101_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectusers',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectusers',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectUsers',
        ),
    ]
