# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180101_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionusers',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='missionusers',
            name='user',
        ),
        migrations.DeleteModel(
            name='MissionUsers',
        ),
    ]
