# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180101_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='阶段进度'),
        ),
    ]
