# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 14:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_auto_20180110_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='记录描述')),
            ],
            options={
                'verbose_name': '子记录',
                'verbose_name_plural': '子记录',
            },
        ),
        migrations.AddField(
            model_name='missions',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='预计完成时间'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='任务描述'),
        ),
        migrations.AddField(
            model_name='records',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Missions', verbose_name='所属任务'),
        ),
        migrations.AddField(
            model_name='records',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录登记人'),
        ),
    ]
