# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171014_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
