# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171014_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_project_leader',
            field=models.BooleanField(default=False, verbose_name='项目负责标记'),
        ),
    ]
